feat: ✨ yarn pnp commands run with `node -r .pnp.js`
folke/ultra-runner pull request #142
Opened 2020-12-09 10:58 UTC by remorses

fix #141

2020-12-09 11:01 UTC, remorses commented
Time comparison in a large yarn pnp monorepo (cannot share link, it's from work)

Yarn
```
❯ time yarn tsc --version
Version 3.7.5
yarn tsc --version  3,64s user 0,39s system 145% cpu 2,775 total
```

Ultra
```
❯ time bin/ultra.js tsc --version
✔ $ tsc --version 514ms
  │ Version 3.7.5
  │ 
success ✨ Done in 1.273s
bin/ultra.js tsc --version  1,70s user 0,20s system 147% cpu 1,292 total
```

2020-12-12 16:00 UTC, merceyz commented on src/runner.ts
> +    const dir = findUp(".pnp.js", cwd)
Can be either `.pnp.js` or `.pnp.cjs`

2020-12-13 13:33 UTC, folke requested changes
Looks good to me except for the comment by @merceyz 

If you can resolve that one, I'll merge this and push a new release.

Thank you!

2020-12-13 15:26 UTC, remorses commented
Added support for `.pnp.cjs`

2020-12-13 18:11 UTC, folke approved these changes

2020-12-13 18:11 UTC, merged

2020-12-13 18:22 UTC, folke commented
Merged and released! 🚀